on:
  push:
    branches:
      - main
      - Next
  pull_request:

jobs:
  send_embed:
    runs-on: MW
    name: Poslat Embed o novém statusu

    steps:
      - name: Spustit Github Actions Status Embed Action
        uses: SebastiaanZ/github-status-embed-for-discord@main
        with:
          webhook_id: '1047616156866973828'
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          status: 'success'
